Updated code samples with breaking changes
dojo-engineering/dojo-samples pull request #53
Opened 2024-02-06 02:06 UTC by monica-m-ps

itemLines.caption -> itemLines.name

Cannot update C# and PHP samples as the SDKs need to be updated first.

Quick question:

We have added 
`cashbackAmount`
`serviceChargeAmount`
`itemLines.category`
`itemLines.modifiers`

Should we update the samples to add these fields too? 
We currently have the following fields under `itemLines`:
```
"itemLines": [
            {
                "id": "item 1",
                "quantity": 4,
                "name": "Dog socks",
                "amountTotal": {
                    "value": 400,
                    "currencyCode": "GBP"
                }
            },
   ]
```

2024-02-06 15:17 UTC, zianyusuf approved these changes
Looks good to me

2024-02-06 15:19 UTC, zianyusuf commented
Yes it's worth including cashbackAmount, serviceChargeAmount, itemLines.category, itemLines.modifiers to the requests if possible please.

2024-02-06 15:20 UTC, zianyusuf requested changes
Include cashbackAmount, serviceChargeAmount, itemLines.category, itemLines.modifiers to the requests if possible please.

2024-04-30 12:59 UTC, monica-m-ps commented
Closing PR as this is no longer valid. We have an updated spec so will open up another PR according to that spec.

2024-04-30 12:59 UTC, closed without merging